language: php

git:
  depth: 2

matrix:
  include:
    - php: hhvm-3.9
      sudo: required
      dist: trusty
      group: edge
    - php: 7.1
    - php: 7.0
      env:
      - LINT=true
    - php: 5.6
    - php: 5.5
    - php: 5.4
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_script:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - composer install -n

script:
  - if [[ $LINT = true ]]; then
      composer cs-lint;
    fi
  - composer test
