language: php

matrix:
  include:
    - php: hhvm
    - php: nightly
    - php: 7.1
    - php: 7.0
      env:
      - DISABLE_XDEBUG=true
    - php: 5.6
      env:
      - DISABLE_XDEBUG=true
    - php: 5.5
      env:
      - DISABLE_XDEBUG=true
    - php: 5.4
      env:
      - DISABLE_XDEBUG=true
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_script:
  - if [[ $DISABLE_XDEBUG = true ]]; then
      phpenv config-rm xdebug.ini;
    fi
  - composer self-update
  - composer install -n

script:
  - composer cs-lint
  - composer test
