language: php

git:
  depth: 2

matrix:
  include:
    - php: hhvm
    - php: nightly
    - php: 7.2
    - php: 7.1
    - php: 7.0
      env:
      - LINT=true
    - php: 5.6
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_script:
  - composer self-update
  - composer install -n

script:
  - if [[ $LINT = true ]]; then
      composer cs-lint;
    fi
  - composer test
