language: php

env:
  global:
    - disable-xdebug=true

matrix:
  include:
    - php: hhvm
      env: disable-xdebug=false
    - php: nightly
      env: disable-xdebug=false
    - php: 7.1
      env: disable-xdebug=false
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: 5.4
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_script:
  - if [[ $disable-xdebug = true ]]; then
      phpenv config-rm xdebug.ini;
    fi
  - composer self-update
  - composer install -n

script:
  - composer cs-lint
  - composer test
