language: php

php:
  - hhvm
  - nightly
  - 7
  - 5.6
  - 5.5
  - 5.4

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_script:
  - if [[ $TRAVIS_PHP_VERSION != hhvm && $TRAVIS_PHP_VERSION != nightly ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer install -n

script:
  - composer cs-lint
  - composer test
