language: php

php:
  - hhvm
  - 7
  - 5.6
  - 5.5
  - 5.4

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install -n

script:
  - composer test
